# Generated by Django 5.2.8 on 2025-12-03 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_travel_create_by_travel_created_at_travel_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='passenger_list',
            field=models.ManyToManyField(blank=True, related_name='travels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='travel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
